// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5PlUohVoNM3MviFQpcuVhQjZ-PP6M24k',
    appId: '1:935761185347:web:c635ca24c396832ea9a2f6',
    messagingSenderId: '935761185347',
    projectId: 'ecommerce-14c22',
    authDomain: 'ecommerce-14c22.firebaseapp.com',
    storageBucket: 'ecommerce-14c22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0dtF3anv3fvQZgpgk15dlggBcDzTygBw',
    appId: '1:935761185347:android:38570678a3e144f9a9a2f6',
    messagingSenderId: '152924223569',
    projectId: 'ecommerce-14c22',
    storageBucket: 'ecommerce-14c22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdJvTQHq2rAFgWem-tTegZkgeMIQ8VISE',
    appId: '1:935761185347:ios:de42100cca9a2293a9a2f6',
    messagingSenderId: '935761185347',
    projectId: 'ecommerce-14c22',
    storageBucket: 'ecommerce-14c22.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdJvTQHq2rAFgWem-tTegZkgeMIQ8VISE',
    appId: '1:935761185347:ios:de42100cca9a2293a9a2f6',
    messagingSenderId: '935761185347',
    projectId: 'ecommerce-14c22',
    storageBucket: 'ecommerce-14c22.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5PlUohVoNM3MviFQpcuVhQjZ-PP6M24k',
    appId: '1:935761185347:web:779f98832214334ea9a2f6',
    messagingSenderId: '935761185347',
    projectId: 'ecommerce-14c22',
    authDomain: 'ecommerce-14c22.firebaseapp.com',
    storageBucket: 'ecommerce-14c22.firebasestorage.app',
  );
}
